### ISSUE TITLE
Remove the IIFE scope since it's not necessary

### ISSUE THREAD

**Issue by folkertjan** [dorusth/web-app-from-scratch-18-19#2]
Your program is dependent on named functions and one call in the public scope to call it. There's nothing in other functions that have a need for the IIFE to exist. As for your current program, I'd either put everything in the IIFE or remove the IIFE alltogether.
https://github.com/dorusth/web-app-from-scratch-18-19/blob/f47cd11f530bbe64bde94c71ab00a407b66cb491/week1/public/js/app.js#L5-L34

**Comment by dorusth** [comment]
I changed the use of the IIFE and functionalities to prevent function calls in the IIFE
