### ISSUE TITLE
Fix indentation

### ISSUE THREAD

**Issue by maanlamp** [dorusth/web-app-from-scratch-18-19#4]
https://github.com/dorusth/web-app-from-scratch-18-19/blob/f47cd11f530bbe64bde94c71ab00a407b66cb491/week1/public/js/app.js#L1-L3

Please don't indent multiple variables like this... Just use a second `const` instead of chaining the const declarations.

**Comment by dorusth** [comment]
fixed the variable naming and chaining of the variables
