### ISSUE TITLE
Purpose of the IIFY

### ISSUE THREAD

**Issue by TuriGuilano** [dorusth/web-app-from-scratch-18-19#6]
You declare an IFFY but you also have several global variables, why?

https://github.com/dorusth/web-app-from-scratch-18-19/blob/f47cd11f530bbe64bde94c71ab00a407b66cb491/week1/public/js/app.js#L1-L3

https://github.com/dorusth/web-app-from-scratch-18-19/blob/f47cd11f530bbe64bde94c71ab00a407b66cb491/week1/public/js/app.js#L5

**Comment by dorusth** [comment]
I changed up the code to prevent the use of the global variables and IFFE
